name: main

on:
  push:
    branches:
      - add-customers-model
  schedule:
      - cron: '*/15 * * * *'

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dbt and dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install git python3-pip
          pip install dbt-core dbt-bigquery
      - name: populate
        run: dbt seed
      - name: run tiktok_ads_source
        run: dbt run -s tiktok_ads_source
      - name: run tiktok_ads
        run: dbt run -s tiktok_ads       