name: main

on:
  push:
    branches:
      - add-customers-model
  schedule:
    - cron: '0 21 * * *'  # Runs at 3:00 pm Mexico City time (UTC-6)

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dbt and dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install git python3-pip
          pip install dbt-core
      - name: Run
        run: dbt run -s tiktok_ads_source --profile default
