name: on schedule

on:
  push:
    branches:
      - development
  schedule:
    - cron: "00 07 * * *"
  


jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dbt and dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install git python3-pip
          pip install dbt-core dbt-bigquery
      - name: Debug
        env:
          DBT_PPROFILES_DIR: ./

          BIGQUERY_DB_NAME: ${{ secrets.BIGQUERY_DB_NAME }}
          BIGQUERY_DB_SCHEMA: ${{ secrets.BIGQUERY_DB_SCHEMA }}
          BIGQUERY_CREDS: ${{ secrets.BIGQUERY_CREDS }}        
        run: dbt debug --profiles-dir .     
            
  